folio-org/mod-pubsub

- mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishTest.java
We should remove these checks as they show inconsistent results after audit service was rewritten as vertx proxy service.
> Fixed tests

- mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
To avoid confusion on startup of the module it is better to remove any default dependencies for now. We'll add the necessary ones when they're needed.
> Removed permissions

- descriptors/ModuleDescriptor-template.json
Getting an error on the reference environments:
```
13:55:02.716 [vert.x-worker-thread-0] ERROR LiquibaseUtil        [10822eqId] Error while initializing schema for the module
liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: Out of memory
```
clears up if I manually increase memory, this change is to update the defaults.
> increase memory

- descriptors/ModuleDescriptor-template.json
-XX:+HeapDumpOnOutOfMemoryError param ensures that a heap dump file is recorded when module crashes with OOM. It should allow us to get a heap dump from the env when it happens and quickly understand what's consuming all the memory.
> Added java_options param to create a heap dump on OOM error

- NEWS.md
- README.md
- descriptors/ModuleDescriptor-template.json
- mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
In order to enable delivery of events implemented in scope of [CIRC-734](https://issues.folio.org/browse/CIRC-734) and [MODFEE-53](https://issues.folio.org/browse/MODFEE-53) to mod-patron-blocks, mod-pubsub must be granted a new pemission:
```
{
"permissionName": "patron-blocks.events.post",
"displayName": "Patron blocks - post event",
"description": "Post events to patron blocks"
}
```
Resolves [MODPUBSUB-96](https://issues.folio.org/browse/MODPUBSUB-96)
> [MODPUBSUB-96] Add permission to send events to mod-patron-blocks

- mod-pubsub-server/pom.xml
folio-liquibase-util v1.0.0 was released, its new development version is 1.1.0-SNAPSHOT, therefore v0.0.1-SNAPSHOT will no longer be available
> Update folio-liquibase-util dependency to v1.0.0

- descriptors/ModuleDescriptor-template.json
- mod-pubsub-server/src/main/java/org/folio/representation/User.java
- mod-pubsub-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/ModTenantApiTest.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
https://issues.folio.org/browse/MODPUBSUB-107 - Show **system** as source in loan action table when lost item fees are paid
Since mod-circulation integration with pub-sub it is required to have a last name for the user in order to properly display source of action at loan action page.
Emma has discussed it with RA SIG and they decided to use **System** as an human identifier of the user (i.e. the last name).
* Add `personal.lastName` property to user json that used [to create the user](https://github.com/folio-org/mod-pubsub/pull/88/files#diff-f11076db34e5ecca90023354b89b08baR250);
* [Do update](https://github.com/folio-org/mod-pubsub/pull/88/files#diff-f11076db34e5ecca90023354b89b08baR142) of the existing user if the property is not present (to cover migration case);
* Add some tests to …
> MODPUBSUB-107: Set/update lastName for the pub-sub user.

- descriptors/ModuleDescriptor-template.json
Do not declare permissions that are defined (required by) other modules.
> Do not declare permissions defined by other modules MODPUBSUB-144

- descriptors/ModuleDescriptor-template.json
- mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
1. Permissions logic changed.
Unite all permissions in "pubsub.events.post".
More info: https://issues.folio.org/browse/MODPUBSUB-145
> MODPUBSUB-145:Add permissions for pubsub user on re-login.

- NEWS.md
- PERSONAL_DATA_DISCLOSURE.md
The purpose of this form is to disclose the types of personal data stored by each module.  This information enables those hosting FOLIO to better manage and comply with various privacy laws and restrictions, e.g. GDPR.
> MODPUBSUB-137 Add personal data disclosure form

- mod-pubsub-server/pom.xml
- mod-pubsub-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/ModTenantApiTest.java
Several problems with this implementation:
1: handler was called without proper response type. It should be
someting like Future.succeededFuture(PostTenantResponse.responseWith...)
Not doing this right will make RMB throw 500.
2: Liquibase and user created always (also when module is disabled
or even purged).
3: using postTenantSync was meant to be used for UNIT TESTING and not
for production code. This means that database setup which may take
a while will be blocking. But it's not a show-stopper.
This commit just makes the post stuff to happen in loadData. This is called
on create/upgrade of a tenant. It also has a much simpler API. However,
because mod-pubsub unit tests aren't set up for async operation, the
super.postTenantSync is kept for now. It should eventually removed, so
that …
> Fix tenant init MODPUBSUB-148

- NEWS.md
- mod-pubsub-client/src/main/java/org/folio/util/pubsub/PubSubClientUtils.java
- mod-pubsub-client/src/test/java/org/folio/config/TestConfig.java
- mod-pubsub-client/src/test/java/org/folio/util/pubsub/PubSubClientTest.java
- mod-pubsub-client/src/test/java/org/folio/util/pubsub/PubSubClientUtilsTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/EventTypeAPITest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/MessagingModulesApiTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/ModTenantApiTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishersApiTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/SubscribersApiTest.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/ConsumerServiceUnitTest.java
Module registration in mod-pubsub fails when MessagingDescriptor contains no publications.
Steps to Reproduce:
- Pick a module that performs registration in mod-pubsub when its TenantAPI is called
- Prepare a MessagingDescriptor with some subscriptions and no publications
- Call module's TenantAPI
Complete future in any case
> MODPUBSUB-152 

- NEWS.md
- folio-kafka-wrapper/pom.xml
- folio-kafka-wrapper/src/main/java/org/folio/kafka/KafkaConfig.java
- folio-kafka-wrapper/src/main/java/org/folio/kafka/cache/KafkaInternalCache.java
- folio-kafka-wrapper/src/main/java/org/folio/kafka/cache/util/CacheUtil.java
Ensure exactly once processing for interaction via Kafka.
Added Kafka Cache for processing events for exactly-once processing. 
More info: https://issues.folio.org/browse/MODINV-373.
Should be merged before: https://github.com/folio-org/mod-inventory/pull/319
> MODINV-373: Ensure exactly once processing for interaction via Kafka.

- mod-pubsub-server/src/main/java/org/folio/services/impl/StartupServiceImpl.java
Fix 404 returned by mod-login when trying to register existing subscribers during module initialization.
Module's implementation of InitAPI fetches a set of existing subscribers, tries to register them as consumers of corresponding Kafka topics and creates a handler for every event type. In order to deliver a message handlers need a valid JWT-token, obtained by loging in user `pub-sub`. However, `OkapiConnectionParams` created within `StartupService#initSubscribers` and used to build a request to mod-login, do not contain any Okapi headers (the map is null), which results in the call to `/authn/login` being made without Okapi headers, most notably `x-okapi-tenant`. Okapi thinks such calls are intended for tenant `supertenant`, so it tries to call supetenant's mod-login, which does not …
> [MODPUBSUB-158] Initialize headers map when registering subscribers after startup

- mod-pubsub-server/src/main/java/org/folio/services/impl/MessagingModuleServiceImpl.java
Fix occasional subscriber registration failures. See [MODPUBSUB-155](https://issues.folio.org/browse/MODPUBSUB-155) for details.
Using `Future#map` instead of `Future#compose` wraps `CompositeFuture` in another `Future` and completes it immediately, without waiting until all the missing event types are created. This means that sometimes we try to create a subscriber before newly created event type makes its way into the DB, thus violating foreign key constraint:
```
{
"message": "insert or update on table \"messaging_module\" violates foreign key constraint \"fk_event_type_id\"",
"severity": "ERROR",
"code": "23503",
"detail": "Key (event_type_id)=(ITEM_CLAIMED_RETURNED) is not present in table \"event_descriptor\".",
"file": "ri_triggers.c",
"line": "3255",
"routine": …
```
> [MODPUBSUB-155] fix incorrect future composition in MessagingModuleServiceImpl

- mod-pubsub-server/src/main/java/org/folio/dao/impl/MessagingModuleDaoImpl.java
- mod-pubsub-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishersApiTest.java
Fix mod-circulation-storage's failure to register as publisher of `LOG_RECORD` events upon enviroment startup.
Before registering a new event publisher, mod-pubsub finds and deletes all existing publisher definitions with the same event type, module role, tenant ID and module name. In order to perform this search when registering mod-circulation as publisher of `LOG_RECORD` events, a query with  the following WHERE clause is used:
```
WHERE TRUE AND module_id LIKE 'mod-circulation-%%.%.%' AND tenant_id = 'diku' AND role = 'PUBLISHER';
```
Unfortunately, pattern `'mod-circulation-%%.%.%'` also matches `mod-circulation-storage-...`, so existing publisher definitions for this module are deleted as well. Since during environment startup mod-circulation-storage is launched first, its …
> [MODPUBSUB-157] mod-circulation-storage doesn't register on pubsub upon environment startup

- NEWS.md
- folio-kafka-wrapper/pom.xml
- folio-kafka-wrapper/src/main/java/org/folio/kafka/KafkaConfig.java
- folio-kafka-wrapper/src/main/java/org/folio/kafka/cache/KafkaInternalCache.java
- folio-kafka-wrapper/src/main/java/org/folio/kafka/cache/exceptions/KafkaInternalCacheInitializationException.java
- folio-kafka-wrapper/src/test/java/org/folio/kafka/cache/KafkaInternalCacheTest.java
* expanded KafkaInternalCache with logic for topic creation with topic cleanup policy `delete`
* set kafkacache.topic.require.compact = false into the kafkacache config to avoid validation for `cleanup.policy = compact`
[MODINV-396](https://issues.folio.org/browse/MODINV-396)
> MODPUBSUB-163 - Kafka Thread Blocked Timeout (KCache)

- mod-pubsub-client/src/main/java/org/folio/rest/client/PubsubClient.java
- mod-pubsub-client/src/main/java/org/folio/util/pubsub/PubSubClientUtils.java
Close HttpClient explicitly in `PubSubClientUtils` to avoid memory leak.
Resolves [MODPUBSUB-166](https://issues.folio.org/browse/MODPUBSUB-166).
Prerequisite for [CIRC-1121](https://issues.folio.org/browse/CIRC-1121).
Bring back explicit closure of `PubsubClient` introduced in #109 but removed in #126.
Results of mod-circulation's heap dump analysis after 1000 checkins:
**BEFORE**
**AFTER**
> [MODPUBSUB-166] Close HttpClient after use in PubSubClientUtils

- NEWS.md
- folio-kafka-wrapper/src/main/java/org/folio/kafka/KafkaConfig.java
- folio-kafka-wrapper/src/main/java/org/folio/kafka/SimpleConfigurationReader.java
- folio-kafka-wrapper/src/main/java/org/folio/kafka/SpringKafkaProperties.java
- folio-kafka-wrapper/src/test/java/org/folio/kafka/KafkaConfigTest.java
- folio-kafka-wrapper/src/test/java/org/folio/kafka/SimpleConfigurationReaderTest.java
to ensure producer/consumer configuration necessary for kafka security needs
* provide necessary properties for kafka security
* ensure properties lookup order: 1)in sys properties, 2)in env variables
* add support for reading necessary spring boot kafka related properties (as an alternative source for properties values)
[MODPUBSUB-171](https://issues.folio.org/browse/MODPUBSUB-171)
https://wiki.folio.org/pages/viewpage.action?spaceKey=~mage.air&title=Kafka+Security
https://wiki.folio.org/pages/viewpage.action?spaceKey=FOLIJET&title=Enabling+SSL+and+ACL+for+Kafka
https://kafka.apache.org/25/documentation.html#security.protocol
https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.integration.spring.kafka.consumer.auto-offset-reset …
> MODPUBSUB-171 - Provide properties for Kafka security in kafka-wrapper

- NEWS.md
- folio-kafka-wrapper/src/main/java/org/folio/kafka/KafkaTopicNameHelper.java
- folio-kafka-wrapper/src/test/java/org/folio/kafka/KafkaTopicNameHelperTest.java
Enable kafka topic to create for tenant where there are less than 4 symbols.
1. Change subscription definition pattern to accept from 1 symbol and more.
2. Tests added for KafkaTopicNameHelper.
3. NEWS updated.
https://issues.folio.org/browse/MODPUBSUB-181
> MODPUBSUB-181: mod-source-record-manager unable to create Kafka topics if tenant ID doesn't match \w{4,}

- NEWS.md
- mod-pubsub-server/pom.xml
- mod-pubsub-server/src/main/java/org/folio/kafka/KafkaConfig.java
- mod-pubsub-server/src/main/java/org/folio/kafka/SpringKafkaProperties.java
- mod-pubsub-server/src/main/java/org/folio/rest/util/SimpleConfigurationReader.java
- mod-pubsub-server/src/test/java/org/folio/kafka/KafkaConfigTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/util/SimpleConfigurationReaderTest.java
Increase security providing security properties for mod-pubsub.
1.Check if sys property exists and applies to producer/consumer.
2. If not check if spring property exists and applies to producer/consumer.
3. If not, apply default (if default provided).
Tests added + NEWS updated.
More info: https://issues.folio.org/browse/MODPUBSUB-182
> MODPUBSUB-182: Provide properties for Kafka security in mod-pubsub

- folio-kafka-wrapper/pom.xml
- folio-kafka-wrapper/src/main/java/org/folio/kafka/KafkaConsumerWrapper.java
- folio-kafka-wrapper/src/test/java/org/folio/kafka/KafkaConsumerWrapperTest.java
currently, when loadLimit parameter is initialized through the KafkaConsumerWrapper constructor the threshold for consumer resuming is initialized as 0.
* init the threshold (loadBottomGreenLine) for consumer resuming according to the load limit
* add test
[MODPUBSUB-185](https://issues.folio.org/browse/MODPUBSUB-185)
> MODPUBSUB-185 - Adjust the threshold at which the consumer can be resumed according to the load limit

- NEWS.md
- folio-kafka-wrapper/src/main/java/org/folio/kafka/KafkaConfig.java
- folio-kafka-wrapper/src/main/java/org/folio/kafka/SpringKafkaProperties.java
- mod-pubsub-server/src/main/java/org/folio/kafka/KafkaConfig.java
- mod-pubsub-server/src/main/java/org/folio/kafka/SpringKafkaProperties.java
**ssl.endpoint.identification.algorithm** option has to be set to null regarding [Kafka docs](https://docs.confluent.io/4.0.0/kafka/authentication_ssl.html#optional-settings) to allow SSL connection using DNS CNAME
Add **ssl.endpoint.identification.algorithm** property
https://docs.confluent.io/4.0.0/kafka/authentication_ssl.html#optional-settings
> MODPUBSUB-186 Provide 'ssl.endpoint.identification.algorithm' property

- folio-kafka-wrapper/src/main/java/org/folio/kafka/KafkaConfig.java
If max.request.size is not set as ENV variable in a module that uses folio-kafka-wrapper, it's value is initialised to 0 and put into Producer props, which overwrites default Kafka values
Check if max.request.size is set before putting to Producer props, if not - leave it to Kafka default
> MODPUBSUB-192 Check if max.request.size is set before putting it as producer props

- descriptors/ModuleDescriptor-template.json
mod-permissions 6.0.0 has an extra security check to avoid general users assigning
arbitrary permissions.
https://issues.folio.org/browse/MODPUBSUB-209
> Add perms.users.assign.immutable MODPUBSUB-209

- mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
At this point, when the error is reported, the message from mod-permissions is not logged.
Include that in the diagnostic.
> Extend diagnostics for failed pubsub user creation

- mod-pubsub-server/src/main/java/org/folio/dao/MessagingModuleDao.java
- mod-pubsub-server/src/main/java/org/folio/dao/impl/MessagingModuleDaoImpl.java
- mod-pubsub-server/src/main/java/org/folio/services/MessagingModuleService.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/MessagingModuleServiceImpl.java
- mod-pubsub-server/src/test/java/org/folio/dao/impl/MessagingModuleDaoImplUnitTest.java
`Future<Boolean>` is used with true indicating success and false indicating failure. This results in two ways how a failure can be propagated: As a failing Future, or as a succeeding Future returning false. This results in bloated code and is error-prone.
The idiomatic way is to only use the built-in success/failure indicator of the Future and to use Void as the type: `Future<Void>`.
Approach:
Replace `Future<Boolean>` by `Future<Void>` and use the built-in error handling of Vert.x' Future: https://github.com/folio-org/raml-module-builder/blob/master/doc/futurisation.md#result-and-error-handling
MessagingModuleDao#delete(String id) is removed because it is not used.
The Boolean was set to "rowCount() == 1", however, the Boolean was not checked, a false Boolean was considered a successful …
> MODPUBSUB-213: Replace Future<Boolean> in MessagingModuleDao

- mod-pubsub-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
- mod-pubsub-server/src/main/java/org/folio/services/SecurityManager.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/ModTenantApiTest.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/ConsumerServiceUnitTest.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
Future<Boolean> is used with true indicating success and false indicating failure. This results in two ways how a failure can be propagated: As a failing Future, or as a succeeding Future returning false. This results in bloated code and is error-prone.
The idiomatic way is to only use the built-in success/failure indicator of the Future and to use Void as the type: `Future<Void>`.
This reveals that SecurityManagerImpl#addPermissions and #assignPermissions don't properly propagate failures.
ModTenantApiTest#shouldLoginWithEnvVarCredentials was adopted accordingly.
Switching from `Future<Boolean>` to `Future<Void>` also allowed to merge SecurityManager#loginPubSubUser and #getJWTToken.
Lessons learned:
Replacing `Future<Boolean>` by `Future<Void>` results in less code and uncovers bugs.
> MODPUBSUB-212: Replace Future<Boolean> by Future<Void> SecurityManager

- README.md
- descriptors/ModuleDescriptor-template.json
- mod-pubsub-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
- mod-pubsub-server/src/main/java/org/folio/rest/util/OkapiConnectionParams.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/ModTenantApiTest.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
The new strategy only involves handling 404, 201, 200 codes -
rest is considered an error. A permission user is either created
or updated with permissions necessary. If mod-users user is created
and mod-pubsub crashes before mod-permissions, then mod-permissions
user is created as it should be.
Do not supply an invalid X-Okapi-token "dummy" anymore.
Do not get token during tenant init. It's not needed for anything during init.
> Fix create/update pubsub user MODPUBSUB-221

- mod-pubsub-client/src/main/java/org/folio/rest/client/WebClientProvider.java
- mod-pubsub-client/src/main/java/org/folio/rest/util/OkapiConnectionParams.java
- mod-pubsub-server/src/main/java/org/folio/rest/impl/PubSubImpl.java
Do not allow OkapiConnectionParams to be constructed without supplying a vertx handle.
A one line change to mod-circulation-storage and mod-circulation.
The other modules do not require code changes and tests pass on them.
> OkapiConnectionParams takes vertx parameter

- mod-pubsub-server/pom.xml
- mod-pubsub-server/src/main/java/org/folio/rest/util/ExceptionHelper.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
- pom.xml
Remove org.raml.jaxrs:jaxrs-code-generator:3.0.2 runtime dependency.
jaxrs-code-generator is not needed and has many vulnerable dependencies:
* org.mozilla:rhino@1.7R4 https://security.snyk.io/vuln/SNYK-JAVA-ORGMOZILLA-1314295
* com.google.code.gson:gson@2.5 https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327
* org.codehaus.jackson:jackson-mapper-asl@1.9.1 https://nvd.nist.gov/vuln/detail/CVE-2019-10172
* commons-io:commons-io@2.4 https://nvd.nist.gov/vuln/detail/CVE-2021-29425
* org.apache.httpcomponents:httpclient@4.0.1 https://nvd.nist.gov/vuln/detail/CVE-2014-3577, https://nvd.nist.gov/vuln/detail/CVE-2012-6153, https://nvd.nist.gov/vuln/detail/CVE-2011-1498
* org.yaml:snakeyaml@1.15 https://nvd.nist.gov/vuln/detail/CVE-2017-18640
* com.google.guava:guava@19.0 …
> MODPUBSUB-229: Remove jaxrs-code-generator (CVE-2019-10172)

- Jenkinsfile
- README.md
- ramls/pubSub.raml
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-pubsub section of API documentation will be automatically reconfigured:
https://dev.folio.org/reference/api/#explain-gather-config
> FOLIO-3231 Use new api-lint and api-doc CI facilities

- Jenkinsfile
- mod-pubsub-client/pom.xml
- mod-pubsub-server/pom.xml
- mod-pubsub-server/src/test/java/org/folio/rest/impl/PubSubIT.java
- pom.xml
Update folio-liquibase-util from 1.3.0 to 1.4.1. This updates liquibase from 4.7.1 to 4.9.0 fixing https://nvd.nist.gov/vuln/detail/CVE-2022-0839
Update liquibase from 3.4.1 to 4.9.0 fixing https://nvd.nist.gov/vuln/detail/CVE-2022-0839
Update RMB from 33.2.4 to 33.2.8. This updates jackson-databind from 2.13.1 to 2.13.2.1 fixing https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Update Vert.x from 4.2.4 to 4.2.6.
> MODPUBSUB-231: Update dependencies fixing CVE-2022-0839, CVE-2020-36518

- pom.xml
Update from jackson-databind 2.13.1 to 2.13.2.1 fixing StackOverflow exception
and denial of service via a large depth of nested objects:
https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Approach:
Bump RMB from 33.2.8 to 33.2.9 and Vert.x from 4.2.6 to 4.2.7.
vertx-dependencies contain jackson with the fix.
> MODPUBSUB-232: jackson-databind 2.13.2.1 (CVE-2020-36518)

- mod-pubsub-client/pom.xml
- mod-pubsub-server/pom.xml
- pom.xml
Upgrade folio-di-support from folio-di-support:1.2.0 (mod-pubsub-client) and folio-di-support:1.4.1 (mod-pubsub-server) to folio-di-support:1.5.1 (each).
This indirectly upgrades spring-beans from 5.2.8 to 5.3.19 fixing Remote Code Execution: https://nvd.nist.gov/vuln/detail/CVE-2022-22965
> MODPUBSUB-233: folio-di-support 1.5.1, spring-beans 5.3.19

- NEWS.md
- mod-pubsub-client/pom.xml
- mod-pubsub-server/pom.xml
- pom.xml
Release 2.5.1 with bug fixes, most of them fix security vulnerabilities.
Most notable fix:
Spring4Shell ([FOLIO-3466](https://issues.folio.org/browse/FOLIO-3466) = [MODPUBSUB-233](https://issues.folio.org/browse/MODPUBSUB-233)): Upgrade spring-beans from 5.2.8 to 5.3.19 fixing Remote Code Execution: https://nvd.nist.gov/vuln/detail/CVE-2022-22965
> MODPUBSUB-234: Release 2.5.1

- pom.xml
How to reproduce:
Use JDK of Java 17.
```
mvn clean install
```
Expected result: Build succeeds
Actual result: Build fails with this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project mod-pubsub-client: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x5843f0e9) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x5843f0e9 -> [Help 1]
```
Solution: Upgrade lombok from 1.18.16 to 1.18.24
Build should be possible when using Java 17 JDK.
Upgrade ombok from 1.18.16 to 1.18.24
> MODPUBSUB-242: Upgrade lombok to 1.18.24 for Java 17

- mod-pubsub-client/pom.xml
- mod-pubsub-server/pom.xml
- pom.xml
Upgrade folio-di-support from 1.5.1 to 1.6.0, this upgrades spring-beans from 5.3.19 to 5.3.20 fixing Denial of Service (DoS): https://nvd.nist.gov/vuln/detail/CVE-2022-22970
Upgrade maven-model from 3.3.9 to 3.8.6, this upgrades plexus-utils from 3.0.22 to 3.3.1 fixing these vulnerabilities: https://app.snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSPLEXUS-31521 , https://app.snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSPLEXUS-461102
Upgrade postgresql from 42.3.3 to 42.5.0 fixing SQL Injection: https://nvd.nist.gov/vuln/detail/CVE-2022-31197
Upgrade RMB from 34.0.0 to 34.0.2.
Upgrade Vert.x from 4.2.7 to 4.3.3.
Upgrade folio-liquibase-util from 1.4.1 to 1.5.1.
Upgrade caffeine from 2.8.5 to 3.1.1.
Upgrade log4j from 2.17.1 to 2.18.0.
Upgrade scala-library from 2.13.1 to 2.13.8.
Upgrade kafka-clients from 3.1.0 …
> MODPUBSUB-246: Upgrade dependencies fixing vulnerabilities

- mod-pubsub-client/pom.xml
- mod-pubsub-server/pom.xml
- pom.xml
Upgrade kafka-clients from 3.2.1 to 3.2.3. This fixes an out-of-memory vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-34917
Remove unused dependencies from pom.xml: scala-library, kafka-clients (from mod-pubsub-client), kafka-junit (from mod-pubsub-client).
> MODPUBSUB-251: kafka-clients 3.2.3 fixing out-of-memory vulnerability

- mod-pubsub-server/src/main/java/org/folio/rest/util/OkapiConnectionParams.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/ConsumerServiceUnitTest.java
A record in logs that the user with the barcode checked out the item
- remove invalid userId from headers for token invalidation
Resolves: [MODPUBSUB-248](https://issues.folio.org/browse/MODPUBSUB-248)
> MODPUBSUB-248 Invalid token ConsumerServiceImpl while delivering LOG_RECORD event

- mod-pubsub-server/pom.xml
- mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
- pom.xml
Resolves [MODPUBSUB-245](https://issues.folio.org/browse/MODPUBSUB-245) - tests fail if kafka service is already running
use testcontainers kafka instead of kafka-junit in order not to depend on local env
> MODPUBSUB-245 use testcontainers kafka instead of kafka-junit in order not to depend on local env

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- ramls/pubSub.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODPUBSUB-26 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- README.md
- mod-pubsub-client/pom.xml
- mod-pubsub-server/pom.xml
- mod-pubsub-server/src/main/java/org/folio/config/ApplicationConfig.java
- mod-pubsub-server/src/main/java/org/folio/kafka/PubSubConfig.java
- mod-pubsub-server/src/main/java/org/folio/services/cache/Cache.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java
- mod-pubsub-server/src/test/java/org/folio/kafka/PubSubConfigTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishTest.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/ConsumerServiceUnitTest.java
To reduce the number of partitions needed for a FOLIO cluster with a large number of tenants, mod-pubsub will publish messages to a single topic per event type instead of multiple topics for each tenant.
Modify PubSubConfig to output a tenant collection topic is a environment variable is set. The default operation is to produce messages to topics for each tenant.
https://issues.folio.org/browse/MODPUBSUB-270
> MODPUBSUB-270 enable tenant collection topics

- mod-pubsub-server/src/main/java/org/folio/dao/impl/AuditMessageDaoImpl.java
- mod-pubsub-server/src/main/java/org/folio/dao/impl/EventDescriptorDaoImpl.java
- mod-pubsub-server/src/main/java/org/folio/dao/impl/MessagingModuleDaoImpl.java
- pom.xml
Use new RMB read-only APIs in order to benefit from read-write DB access split.
Resolves [MODPUBSUB-267](https://issues.folio.org/browse/MODPUBSUB-267).
Follow guide provided in [FOLIO-3753](https://issues.folio.org/browse/FOLIO-3753).
> MODPUBSUB-267: Use new RMB read-only APIs

- mod-pubsub-server/src/main/java/org/folio/representation/User.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
- mod-pubsub-server/src/test/java/org/folio/rest/impl/ModTenantApiTest.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
https://issues.folio.org/browse/MODPUBSUB-274
User type field is required in ECS mode, corresponding changes:
https://github.com/folio-org/mod-users/pull/305/files#diff-c61ac265e749725833c34e88681dd23fd2c267c2de0c62217a27526f50395772L3 
For non ECS mode it is optional, existing system users updated in scope of this PR:
https://github.com/folio-org/mod-users/pull/307
> MODPUBSUB-274. Populate system users with type='system'

- pom.xml
Upgrade dependencies. Resolves [https://issues.folio.org/browse/MODPUBSUB-279](MODPUBSUB-279).
> MODPUBSUB-279: Upgrade to RMB 35.1.0 and Vertx 4.4.6

- mod-pubsub-server/pom.xml
- mod-pubsub-server/src/main/java/org/folio/services/cache/Cache.java
Performance tests of the Check In/Out workflows show that in Poppy mod-pubsub has a memory leak. Details from [PERF-721](https://issues.folio.org/browse/PERF-721):
Longevity test was conducted for CICO on pcp1 (75 users, 8 hours). During this test mod-pubsub memory consumption increased from 37% to 63%.
Class taking most of the memory - "java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue". At the end of the test it occupies 95% of bytes. There is a big number of events like java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask inside the class. Number of these events at the beginning of the test - 83K, number at the end of the test - 840K.
Resolves: [MODPUBSUB-286](https://issues.folio.org/browse/MODPUBSUB-286)
- override custom executors for Caffeine cache; …
> MODPUBSUB-286 Fix memory leak issue

- mod-pubsub-server/pom.xml
- mod-pubsub-server/src/main/java/org/folio/config/ApplicationConfig.java
- mod-pubsub-server/src/main/java/org/folio/kafka/PubSubKafkaConfig.java
- mod-pubsub-server/src/main/java/org/folio/kafka/PubSubKafkaTopic.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaTopicServiceImpl.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/StartupServiceImpl.java
- mod-pubsub-server/src/main/java/org/folio/services/publish/PublishingServiceImpl.java
- mod-pubsub-server/src/test/java/org/folio/kafka/PubSubKafkaConfigTest.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/ConsumerServiceUnitTest.java
Add support for SSL-enabled Kafka instances.
Use [folio-kafka-wrapper](https://github.com/folio-org/folio-kafka-wrapper) to create topics. This ensures that Kafka admin client is created with SSL-related properties.
> MODPUBSUB-290 Use folio-kafka-wrapper to create topics

- NEWS.md
- mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java
- mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java
- mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
https://folio-org.atlassian.net/browse/EUREKA-79
When the system user is disabled, mod-pubsub still tries to obtain a token for the system user.
- return empty system user token while system user creation is disabled
- add test
> EUREKA-79: skip retrieving token if system user is disabled

- pom.xml
https://folio-org.atlassian.net/browse/MODPUBSUB-309
Fix security vulnerabilities.
Upgrade kafka-client from 3.6.0 to 3.9.0 fixing
* https://www.cve.org/CVERecord?id=CVE-2023-43642 Allocation of Resources Without Limits or Throttling
* https://www.cve.org/CVERecord?id=CVE-2023-34455 Denial of Service (DoS)
* https://www.cve.org/CVERecord?id=CVE-2023-34454 compress Integer Overflow or Wraparound
* https://www.cve.org/CVERecord?id=CVE-2023-34453 shuffle Integer Overflow or Wraparound
* https://www.cve.org/CVERecord?id=CVE-2024-56128 SCRAM SASL_PLAINTEXT Incorrect Implementation of Authentication Algorithm
* https://www.cve.org/CVERecord?id=CVE-2024-31141  ConfigProviders Files or Directories Accessible to External Parties
Upgrade folio-di-support from 2.1.0 to 2.2.0. This indirectly …
> MODPUBSUB-309: kafka-clients 3.9.0, folio-di-support 2.2.0, vertx 4.5.11

- mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
Add missing event handler permissions for mod-circulation and mod-patron-blocks
[MODPUBSUB-315](https://folio-org.atlassian.net/browse/MODPUBSUB-315)
> MODPUBSUB-315: Add missing event hanlder permissions for Okapi
