folio-org/mod-pubsub

NEWS.md, mod-pubsub-server/src/main/resources/liquibase/module/scripts/v-0.0.1/2019-14-08--14-00-create-module-table.xml, mod-pubsub-server/src/main/resources/liquibase/module/scripts/v-0.0.1/2019-14-08--14-00-pub-sub-storage-setup.xml, mod-pubsub-server/src/main/resources/liquibase/module/scripts/v-0.0.1/2019-14-08--15-00-create-event_type-table.xml, mod-pubsub-server/src/main/resources/liquibase/module/scripts/v-0.0.1/2019-14-08--16-00-create-messaging_module-table.xml
[pub-sub design](https://github.com/folio-org/rfcs/blob/12c2ffc0da5768ec1e183ba124a83dc75a1662d1/text/0000-pub-sub.md)
mod-pub-sub register ER-diagram:
=> MODPUBSUB-7 - Design register for Publishers, Subscribers and Events

NEWS.md, ramls/auditMessage.json, ramls/auditMessagePayload.json, ramls/auditMessageState.json
=> MODPUBSUB-3 Added schemas for Audit Trail

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-pubsub-server/src/main/java/org/folio/dao/EventDescriptorDao.java, mod-pubsub-server/src/main/java/org/folio/dao/MessagingModuleDao.java, mod-pubsub-server/src/main/java/org/folio/dao/ModuleDao.java, mod-pubsub-server/src/main/java/org/folio/dao/impl/EventDescriptorDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/dao/impl/MessagingModuleDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/dao/impl/ModuleDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/dao/util/DbUtil.java, mod-pubsub-server/src/main/java/org/folio/rest/impl/PubSubImpl.java, mod-pubsub-server/src/main/java/org/folio/services/MessagingModuleService.java, mod-pubsub-server/src/main/java/org/folio/services/impl/MessagingModuleServiceImpl.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/EventTypeAPITest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishersApiTest.java, ramls/messagingModuleCollection.json, ramls/pubSub.raml
[pub-sub endpoints description](https://github.com/TarasSpashchenko/rfcs/blob/rfc/pub-sub/text/0000-pub-sub.md#high-level-solution-structure)
=> MODPUBSUB-37 - Create Publisher register API

NEWS.md, mod-pubsub-server/src/main/java/org/folio/dao/impl/AuditMessageDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/rest/impl/PubSubImpl.java, mod-pubsub-server/src/main/java/org/folio/services/PublishingService.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaPublishingServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/PublishingServiceImpl.java, mod-pubsub-server/src/main/resources/liquibase/tenant/scripts/v-0.0.1/2019-11-08--15-00-change-audit_message-table.xml, mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/AuditMessageAPITest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishTest.java, ramls/auditMessage.json, ramls/auditMessageState.json
AuditMessageService will be remade as Vertx service proxy in scope of https://issues.folio.org/browse/MODPUBSUB-49
=> MODPUBSUB-43 Created Publishing Service

NEWS.md
(cherry picked from commit 4bfcf56)
=> Updated news

Jenkinsfile
Enables kubernetes deployment step in CI.
=> deploy pubsub on kubernetes

Jenkinsfile, NEWS.md, mod-pubsub-server/src/main/java/org/folio/kafka/KafkaConfig.java
JIRA-ticket: https://issues.folio.org/browse/MODPUBSUB-34
1. HealthCheck created for "/admin/health".
2. Default values for Parameters added.
=> MODPUBSUB-34: Configure HealthCheck for docker image.

README.md
1. 'README.md'- file was updated.
=> MODPUBSUB-65:Extend documentation for mod-pubsub.

mod-pubsub-client/.gitignore, mod-pubsub-client/pom.xml, mod-pubsub-server/.gitignore, mod-pubsub-server/pom.xml
Bug in liquebase old version
updated to the new one
=> MODPUBSUB-76 mod-pubsub filling container filesystem

mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
https://issues.folio.org/browse/MODPUBSUB-86 - Grant pub-sub user with 'circulation.handlers.all' permissions.
=> MODPUBSUB-86: Grant pub-sub user with 'circulation.handlers.all'

descriptors/ModuleDescriptor-template.json
Pubsub sends POST request to **/authn/login** and **/authn/credentials** endpoints. @craigmcnally please verify that contract for these endpoint was not changed
=> Update dependency on login interface

NEWS.md, mod-pubsub-server/src/main/java/org/folio/services/cache/Cache.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java, mod-pubsub-server/src/test/java/org/folio/services/impl/ConsumerServiceUnitTest.java, mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
Sometimes files don't finish processing, and it's not clear why
=> MODPUBSUB-105 Sometimes files don't finish processing, and it's not clear why

mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java, mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
=> MODDATAIMP-309 - Data Import stops when trying to load a large file to folio-snapshot-load

mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
[MODAUD-15](https://issues.folio.org/browse/MODAUD-15) - LogEventListener for mod-audit
Add mod-audit permissions (audit-data.events.post) to "PubSub" User.
=> MODAUD-15 - LogEventListener for mod-audit

Dockerfile, Jenkinsfile, NEWS.md, README.md, mod-pubsub-server/src/main/java/org/folio/kafka/KafkaConfig.java
1. Default values from ENV_VARIABLES removed.
2. Env variables added to the dockerfile.
3. Readme updated
4. News updated
=> MODPUBSUB-110: Make env variables required for module deployment

NEWS.md, mod-pubsub-server/src/main/java/org/folio/dao/impl/AuditMessageDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/rest/impl/PubSubImpl.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/AuditMessageAPITest.java
1.Check added: if "endDate" without time, then concat the last second of the day.
2.Tests added.
3.NEWS updated.
=> MODPUBSUB-126: GET pubsub/history does not return audit messages[BUGFIX]

NEWS.md, mod-pubsub-server/src/main/resources/liquibase/module/scripts/v-0.0.1/2020-10-01--13-00-remove-invalid-module-names.xml
1.Script added.
2. NEWS updated.
=> MODPUBSUB-129: Create script that would delete module subscriptions with "_" in their names[BUGFIX].

NEWS.md, mod-pubsub-server/src/main/java/org/folio/kafka/PubSubConfig.java
1. ModuleName and version were added to Kafka group and topic.
=> MODPUBSUB-139: Multiple versions of mod-pubsub in the same environment consume events for all tenants.

PULL_REQUEST_TEMPLATE.md
https://issues.folio.org/browse/MODDATAIMP-360
Adding default PR template such as what has been used in other FOLIO repos  https://github.com/folio-org/mod-kb-ebsco-java/blob/master/PULL_REQUEST_TEMPLATE.md
- added default template
=> MODDATAIMP-360 Add PR template

mod-pubsub-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/ModTenantApiTest.java
The unit tests are a little more complicated due to this.
=> Make TenantAPI asynchonous MODPUBSUB-149

mod-pubsub-server/src/main/java/org/folio/services/publish/PublishingServiceImpl.java
Fix memory leak.
Close Kafka producer once a message is sent.
Tested by analyzing heap dump before and after the fix.
Resolves [MODPUBSUB-161](https://issues.folio.org/browse/MODPUBSUB-161).
=> [MODPUBSUB-161] Explicitly close KafkaProducer after sending message

NEWS.md, folio-kafka-wrapper/pom.xml, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
[MODPUBSUB-174](https://issues.folio.org/browse/MODPUBSUB-174)
Release PubSub v2.1.0
=> Tmp release 2.1.0

mod-pubsub-client/src/main/java/org/folio/util/pubsub/support/PomUtils.java, mod-pubsub-client/src/test/java/org/folio/util/pubsub/PubSubClientUtilsTest.java
Resolves [MODPUBSUB-176](https://issues.folio.org/browse/MODPUBSUB-176)
=> MODPUBSUB-176 Remove everything after dash in the moduleId

NEWS.md, folio-kafka-wrapper/pom.xml, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
Resolves [MODPUBSUB-175](https://issues.folio.org/browse/MODPUBSUB-175)
=> Tmp release 2.2.0

NEWS.md, folio-kafka-wrapper/pom.xml, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
Resolves [MODPUBSUB-180](https://issues.folio.org/browse/MODPUBSUB-180)
=> Tmp release 2.3.0

folio-kafka-wrapper/src/main/java/org/folio/kafka/KafkaConsumerWrapper.java
Increase observability of operations with Kafka
By writing more log records into KafkaConsumerWrapper
=> Improve logging

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
Resolves: [MODPUBSUB-197](https://issues.folio.org/browse/MODPUBSUB-197)
=> Tmp release 2.4.0

mod-pubsub-server/src/main/java/org/folio/rest/util/RestUtil.java
https://issues.folio.org/browse/MODPUBSUB-201
Avoid socket leak
By creating only one WebClient per Vert.x instance, rather than for each HTTP request.
This can be simplified further.. Saving Vert.x instance in OkapiConnectionParams is redundant and just adds complexity.
=> Fix socket leak for HTTP requests MODPUBSUB-201

pom.xml
[MODPUBSUB-204](https://issues.folio.org/browse/MODPUBSUB-204)
Upgrading to RMB v33.0.4 and Log4j v2.16.0
=> MODPUBSUB-204 Upgrade to RMB 33.0.4, Log4j 2.16.0

NEWS.md, folio-kafka-wrapper/pom.xml, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
=> Bugfix release 2.3.5

mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java, mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java
Previously the code ignored errors. Why? Are there status
codes that should be ignored?
=> Do not ignore errors MODPUBSUB-210

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
=> Bugfix release 2.4.3

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
=> Release 2.5.0

mod-pubsub-server/src/main/java/org/folio/dao/EventDescriptorDao.java, mod-pubsub-server/src/main/java/org/folio/dao/impl/EventDescriptorDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/services/EventDescriptorService.java, mod-pubsub-server/src/main/java/org/folio/services/impl/EventDescriptorServiceImpl.java, mod-pubsub-server/src/test/java/org/folio/dao/impl/EventDescriptorDaoImplTest.java
[MODPUBSUB-214](https://issues.folio.org/browse/MODPUBSUB-214)
_Replace Future<Boolean> by Future<Void> in EventDescriptorDao_
=> MODPUBSUB-214: Replace Future<Boolean> by Future<Void> in EventDescriptorDao

mod-pubsub-server/src/main/java/org/folio/services/ConsumerService.java, mod-pubsub-server/src/main/java/org/folio/services/MessagingModuleService.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/MessagingModuleServiceImpl.java
[MODPUBSUB-215](https://issues.folio.org/browse/MODPUBSUB-215)
_Replace Future<Boolean> by Future<Void> in ConsumerService_
=> MODPUBSUB-215: Replace Future<Boolean> by Future<Void> in ConsumerService

mod-pubsub-server/src/main/java/org/folio/services/KafkaTopicService.java, mod-pubsub-server/src/main/java/org/folio/services/MessagingModuleService.java, mod-pubsub-server/src/main/java/org/folio/services/PublisherService.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaPublisherServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaTopicServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/MessagingModuleServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/publish/PublishingService.java, mod-pubsub-server/src/main/java/org/folio/services/publish/PublishingServiceImpl.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/MessagingModulesApiTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishersApiTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/SubscribersApiTest.java
https://issues.folio.org/browse/MODPUBSUB-217
Replace `Future<Boolean>` by `Future<Void>` for
- KafkaTopicService
- MessagingModuleService
-  PublisherService
=> MODPUBSUB-217 Replace Future<Boolean> by Future<Void> in KafkaTopicService

README.md
Have documentation corresponding to current module processes up to date
Readme update
https://issues.folio.org/browse/MODPUBSUB-94
=> MODPUBSUB-94 Document how to set-up permissions for event callback API

README.md
- Have documentation related to event callback API endpoint
- Readme update
https://issues.folio.org/browse/MODPUBSUB-91
=> MODPUBSUB-91 Document requirements for an event callback API endpoint

pom.xml
Resolves: https://issues.folio.org/browse/MODPUBSUB-235
=> MODPUBSUB-235 Upgrade RMB to 34.0.0

pom.xml
[MODPUBSUB-252](https://issues.folio.org/browse/MODPUBSUB-252)
=> MODPUBSUB-252 Upgrade to RMB 35.0.0

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
Resolves: [MODPUBSUB-256](https://issues.folio.org/browse/MODPUBSUB-256)
=> [MODPUBSUB-256] Release 2.7.0

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
[MODPUBSUB-261](https://issues.folio.org/browse/MODPUBSUB-261) Release mod-pubsub 2.8.0
[BE release procedure](https://docs.google.com/document/d/1044I8jehoiu243BQ8GIUWCprdIYiDLqBEu5BZMjmCs0/edit)
=> [MODPUBSUB-261] Release 2.8.0

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
Resolves: [MODPUBSUB-263](https://issues.folio.org/browse/MODPUBSUB-263) Release mod-pubsub 2.9.0
[BE release procedure](https://docs.google.com/document/d/1044I8jehoiu243BQ8GIUWCprdIYiDLqBEu5BZMjmCs0/edit)
=> MODPUBSUB-263: Release 2.9.0

Dockerfile, NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
https://issues.folio.org/browse/MODPUBSUB-265 Bugfix release 2.9.1
=> MODPUBSUB-265 Bugfix release 2.9.1

Dockerfile, Jenkinsfile, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
Migrate module from Java 11 to Java 17. Resolves [MODPUBSUB-268)](https://issues.folio.org/browse/MODPUBSUB-268)
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
=> [MODPUBSUB-268] Migrate to Java 17

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
[MODPUBSUB-275](https://issues.folio.org/browse/MODPUBSUB-275)
=> MODPUBSUB-275: Release 2.11.0 (Poppy R2 2023)

README.md, descriptors/ModuleDescriptor-template.json, mod-pubsub-server/src/main/java/org/folio/config/user/SystemUserConfig.java, mod-pubsub-server/src/test/java/org/folio/config/user/SystemUserConfigTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/PubSubIT.java
Remove default password for system user.
Fail at module startup if system variable `SYSTEM_USER_PASSWORD` is not set.
Resolves [MODPUBSUB-278](https://issues.folio.org/browse/MODPUBSUB-278).
=> MODPUBSUB-278: Remove default user password

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, mod-pubsub-server/src/main/java/org/folio/services/cache/Cache.java, pom.xml
Resolves: [MODPUBSUB-288](https://issues.folio.org/browse/MODPUBSUB-288)
=> [MODPUBSUB-288] Release 2.11.3

mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
bump module version to 2.13.0
- `2.12.0-SNAPSHOT` - `2.13.0-SNAPSHOT`
=> MODPUBSUB-289: bump module version to 2.13.0

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
[MODPUBSUB-292](https://folio-org.atlassian.net/browse/MODPUBSUB-292)
=> MODPUBSUB-292: Release 2.13.0

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, mod-pubsub-server/src/main/java/org/folio/config/ApplicationConfig.java, mod-pubsub-server/src/main/java/org/folio/kafka/PubSubKafkaConfig.java, mod-pubsub-server/src/main/java/org/folio/kafka/PubSubKafkaTopic.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaTopicServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/StartupServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/publish/PublishingServiceImpl.java, mod-pubsub-server/src/test/java/org/folio/kafka/PubSubKafkaConfigTest.java, mod-pubsub-server/src/test/java/org/folio/services/impl/ConsumerServiceUnitTest.java, pom.xml
Resolves: [MODPUBSUB-288](https://folio-org.atlassian.net/browse/MODPUBSUB-288)
=> [MODPUBSUB-288] Release v2.13.1

descriptors/ModuleDescriptor-template.json
The permission is added for mod-remote-storage handler. As per MODRS-205
=> MODPUBSUB-296 - Adding the new permission for mod-remote-storage

descriptors/ModuleDescriptor-template.json
To cater to the permission changes in MD file for mod-audit and mod-pubsub.
As per the directions provided here https://folio-project.slack.com/archives/C210RP0T1/p1728648671681809?thread_ts=1728549680.865499&cid=C210RP0T1 PR created.
This pull request and the mod-audit pull request must be merged at the same time:
https://github.com/folio-org/mod-audit/pull/170/files
=> MODPUBSUB-296 - Adding the new permission for mod-audit handler.

mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
As part of https://github.com/folio-org/mod-pubsub/pull/271 and https://github.com/folio-org/mod-pubsub/pull/270 adding the permission csv file
=> adding permission to csv file.

mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
=> Test permissions

.github/workflows/postgres.yml, descriptors/ModuleDescriptor-template.json, mod-pubsub-server/pom.xml, mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/PubSubIT.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishTest.java, pom.xml
Resolves: [MODPUBSUB-298](https://folio-org.atlassian.net/browse/MODPUBSUB-298)
=> [MODPUBSUB-298] Upgrade to RMB 35.3.0

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
[MODPUBSUB-297](https://folio-org.atlassian.net/browse/MODPUBSUB-297)
Update NEWS
=> MODPUBSUB-297: Release 2.15.0

mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODPUBSUB-297
Fix pom versions
=> prepare for next development iteration

descriptors/ModuleDescriptor-template.json, mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv
=> MODPUBSUB-302 - pubsub permission changes.

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, mod-pubsub-server/src/main/resources/permissions/pubsub-user-permissions.csv, pom.xml
=> To release v2.15.1

descriptors/ModuleDescriptor-template.json, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODPUBSUB-295
mod-pubsub-2.15.0-SNAPSHOT.241
Permission protects more than one endpoint: pubsub.event-types.get [/pubsub/event-types [GET], /pubsub/event-types/{eventTypeName} [GET]]
- introduced new permission
=> [MODPUBSUB-295] - Review and cleanup Module Descriptor for mod-pubsub

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODPUBSUB-305
=> Bugfix release 2.15.2

descriptors/ModuleDescriptor-template.json
[MODPUBSUB-307](https://folio-org.atlassian.net/browse/MODPUBSUB-307)
=> MODPUBSUB-307: Add permissions to call circulation event handlers

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
Resolves: [MODPUBSUB-308](https://folio-org.atlassian.net/browse/MODPUBSUB-308)
=> [MODPUBSUB-308] Release 2.15.3

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
Resolves: [MODPUBSUB-310](https://folio-org.atlassian.net/browse/MODPUBSUB-310)
=> MODPUBSUB-310 Release 2.15.4

.dockerignore, .github/workflows/maven.yml, .github/workflows/postgres.yml, Dockerfile, Jenkinsfile, mod-pubsub-client/pom.xml, mod-pubsub-client/src/main/java/org/folio/util/pubsub/PubSubClientUtils.java, mod-pubsub-server/pom.xml, mod-pubsub-server/src/main/java/org/folio/dao/impl/AuditMessageDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/dao/impl/EventDescriptorDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/dao/impl/MessagingModuleDaoImpl.java, mod-pubsub-server/src/main/java/org/folio/kafka/PubSubConfig.java, mod-pubsub-server/src/main/java/org/folio/rest/impl/PubSubImpl.java, mod-pubsub-server/src/main/java/org/folio/rest/util/RestUtil.java, mod-pubsub-server/src/main/java/org/folio/services/impl/EventDescriptorServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaConsumerServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/KafkaPublisherServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/MessagingModuleServiceImpl.java, mod-pubsub-server/src/main/java/org/folio/services/impl/SecurityManagerImpl.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/AuditMessageAPITest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/ModTenantApiTest.java, mod-pubsub-server/src/test/java/org/folio/rest/impl/PublishTest.java, mod-pubsub-server/src/test/java/org/folio/services/impl/ConsumerServiceUnitTest.java, mod-pubsub-server/src/test/java/org/folio/services/impl/SecurityManagerTest.java, pom.xml
=> FOLREL-719: Update to mod-pubsub Java 21

NEWS.md, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODPUBSUB-317
=> Release v2.16.0

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-pubsub-client/pom.xml, mod-pubsub-server/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODPUBSUB-319
=> Bugfix release 2.15.5
